### ISSUE TITLE
what's this for?

### ISSUE THREAD

**Issue by notslang** [carrot/roll#1]
...in comparison to existing solutions like [stellar.js](https://github.com/markdalgleish/stellar.js) or [skrollr](https://github.com/Prinzhorn/skrollr) or [superscrollorama](https://github.com/johnpolacek/superscrollorama).

**Comment by nporteschaikin** [comment]
@slang800 It's written in a style @joshrowley and I discussed.

**Comment by notslang** [comment]
Ah, which style?

**Comment by nporteschaikin** [comment]
All four are implemented in different ways.

**Comment by joshrowley** [comment]
Yeah, we were discussing the best approach to animating one of our case studies. Something that does what skrollr does but without having the API be HTML data attributes. I took a stab at this with [skrilla](https://github.com/carrot/skrilla) which I extracted out of another client project, and I don't think it's that great of an approach (it just calculates the data attributes and adds them to the DOM before skrollr initializes). Seems like a very indirect way of doing it and super tied to skrollr. So @nporteschaikin and I were discussing a direct JS implementation that would do essentially what skrollr does, but with a pure JS API. @nporteschaikin hammered out the initial code yesterday afternoon.

I do want to emphasize @nporteschaikin that you should focus first on using the initial code you showed me for the case study and don't get too bogged down with building this out as a project of its own. I want you to be comfortable with how you're implementing the case study, but just want to make sure you don't get too sidetracked. Or rather, write the minimum needed for this to be useful for the case study, and then once completed you can then flesh this bad boy out further.

**Comment by nporteschaikin** [comment]
Thanks, @joshrowley.

**Comment by jescalan** [comment]
:+1:
