### ISSUE TITLE
Inconsistent Buggy Behavior in Safari

### ISSUE THREAD

**Issue by joshrowley** [carrot/roll#10]
There appears to be some buggy weirdness with the library when in Safari. Sometimes animations don't appear to run at all, the css attributes aren't applied to the elements (and I put in the vendor prefix attributes). I'll have a good example to show you soon, just logging for now.

**Comment by nporteschaikin** [comment]
Thanks @joshrowley. Will iron this out on Monday.

**Comment by nporteschaikin** [comment]
All of these issues are fixed in 0.5.3.
